### PR TITLE
Apply the pattern.filter to every alias (including those without an extension)

### PR DESCRIPTION
**Pull request by brianmgray**
Currently the .filter only applies to the aliases with an extension. But there are also aliases without an extension. If you want to create a filter that affects the alias itself, this means you have to use the extension version. This patch fixes that issue.

### CODE REVIEW

**Comment by joeybaker** [comment]
@brianmgray ping! Any luck with the cleanup?

**Comment by brianmgray** [comment]
Hi Joey,

I am still planning to do this cleanup. We got swamped with a release at work right when you sent this back and I haven't gotten a chance yet. We also have a whole new setup that does not require this anymore so it became less of a priority for me. I still would like to fix my because it is a useful plugin! Just need to make some time.

Thanks,
Brian

**Comment by joeybaker** [comment]
No worries! Thanks for the work!

**Comment by brianmgray** [comment]
Hi Joey, it took me a while to get to it, and by the time I did you had made a lot of progress. I improved the implementation based on some work you had done as well as made the updates you requested. Let me know if there is anything else I can do.

**Comment by brianmgray** [comment]
Looks like this failed due to a lint error. You have a lot of cool stuff setup but I can't run much of it. I'm on a Windows machine. The npm install won't run to pull down the dependencies for the linter. I can't run the scripts. Not sure how to get the hooks to fire. So maybe you can run it and let me know what I need to fix. I'd love to dig into this some time and learn what you have setup. Seems like a good system if I could get it running...

**Comment by roncli** [comment]
I used http://c9.io to run the linter.  Seemed to work well.  It's very strict.

**Comment by joeybaker** [comment]
@roncli good tip on cloud9! It's weird that the linter doesn't run – it's just [jscs](https://github.com/jscs-dev/node-jscs) and jshint. I'll take a look and see what I can do.

**Comment by brianmgray** [comment]
Here is the output I get when I run "npm run lint"

````
$ npm run lint

> remapify@1.4.4 lint c:\Users\bgray\workspaces\scratch\remapify
> npm run jshint && npm run jscs


> remapify@1.4.4 jshint c:\Users\bgray\workspaces\scratch\remapify
> jshint --reporter node_modules/jshint-stylish/stylish.js


√ No problems


> remapify@1.4.4 jscs c:\Users\bgray\workspaces\scratch\remapify
> jscs .

TypeError: Cannot read property 'type' of undefined
    at c:\Users\bgray\workspaces\scratch\remapify\node_modules\jscs\lib\rules\require-multiple-var-decl.js:41:24
    at Array.forEach (native)
    at Object.JsFile.iterateNodesByType (c:\Users\bgray\workspaces\scratch\remapify\node_modules\jscs\lib\js-file.js:328:42)
    at Object.consecutive [as _check] (c:\Users\bgray\workspaces\scratch\remapify\node_modules\jscs\lib\rules\require-multiple-var-decl.js:37:10)
    at Object.module.exports.check (c:\Users\bgray\workspaces\scratch\remapify\node_modules\jscs\lib\rules\require-multiple-var-decl.js:119:28)
    at null.<anonymous> (c:\Users\bgray\workspaces\scratch\remapify\node_modules\jscs\lib\string-checker.js:121:22)
    at Array.forEach (native)
    at StringChecker.checkString (c:\Users\bgray\workspaces\scratch\remapify\node_modules\jscs\lib\string-checker.js:119:35)
    at null.<anonymous> (c:\Users\bgray\workspaces\scratch\remapify\node_modules\jscs\lib\checker.js:40:25)
    at Array.0 (c:\Users\bgray\workspaces\scratch\remapify\node_modules\jscs\node_modules\vow\lib\vow.js:699:39)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "c:\\Users\\bgray\\apps\\ConsolePortable\\util\\nodejs\\\\node.exe" "c:\\Users\\bgray\\apps\\ConsolePortable\\util\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "jscs"
npm ERR! node v0.10.30
npm ERR! npm  v2.1.6
npm ERR! code ELIFECYCLE
npm ERR! remapify@1.4.4 jscs: `jscs .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the remapify@1.4.4 jscs script.
npm ERR! This is most likely a problem with the remapify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     jscs .
npm ERR! You can get their info via:
npm ERR!     npm owner ls remapify
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\Users\bgray\workspaces\scratch\remapify\npm-debug.log

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "c:\\users\\bgray\\apps\\ConsolePortable\\util\\nodejs\\node.exe" "c:\\users\\bgray\\apps\\ConsolePortable\\util\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "lint"
npm ERR! node v0.10.30
npm ERR! npm  v2.1.6
npm ERR! code ELIFECYCLE
npm ERR! remapify@1.4.4 lint: `npm run jshint && npm run jscs`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the remapify@1.4.4 lint script.
npm ERR! This is most likely a problem with the remapify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run jshint && npm run jscs
npm ERR! You can get their info via:
npm ERR!     npm owner ls remapify
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\Users\bgray\workspaces\scratch\remapify\npm-debug.log
````

And here's when I run "npm install"
````
$ npm install
-
> ghooks@0.2.2 install c:\Users\bgray\workspaces\scratch\remapify\node_modules\ghooks
> ./bin/install

'.' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "c:\\users\\bgray\\apps\\ConsolePortable\\util\\nodejs\\node.exe" "c:\\users\\bgray\\apps\\ConsolePortable\\util\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.10.30
npm ERR! npm  v2.1.6
npm ERR! code ELIFECYCLE

npm ERR! ghooks@0.2.2 install: `./bin/install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ghooks@0.2.2 install script.
npm ERR! This is most likely a problem with the ghooks package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./bin/install
npm ERR! You can get their info via:
npm ERR!     npm owner ls ghooks
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\Users\bgray\workspaces\scratch\remapify\npm-debug.log
````

**Comment by joeybaker** [comment]
@brianmgray do you mind posting all that over in #30? I'll see what I can do.

**Pull request closed without merging**
